language: node_js
node_js:
  - "0.10"

addons:
  artifacts:
    s3_region:
      - us-west-2
    paths:
      - test/wraith/shots
      - test/wraith/shots_base

before_install:
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install -g casperjs

install:
  - bundle install
  - bower install
  - npm install

script:
  - grunt
  # - cd test/wraith
  # - wraith latest configs/history.yaml

sudo: false

cache:
  bundler: true
  directories:
    - node_modules
